# Generated by Django 4.0.4 on 2022-06-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('trail_file', models.FileField(upload_to='')),
                ('slug', models.SlugField(unique=True)),
                ('center_lat', models.FloatField(null=True)),
                ('center_lon', models.FloatField(null=True)),
                ('mesh', models.FileField(null=True, upload_to='')),
                ('texture_sat', models.ImageField(null=True, upload_to='')),
                ('texture_trail', models.ImageField(null=True, upload_to='')),
                ('upload_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('notes', models.CharField(max_length=200)),
                ('parent_trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trails.trail')),
            ],
        ),
    ]
