# Generated by Django 4.0.4 on 2022-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='share',
            field=models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC'), ('link', 'LINK')], default='private', max_length=7),
        ),
    ]
