# Generated by Django 4.0.4 on 2022-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_alter_trail_center_lat_alter_trail_center_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_file',
            field=models.FileField(upload_to='test/'),
        ),
    ]
