# Generated by Django 4.0.4 on 2022-06-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_comment_comment_comment_parent_trail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cycling', 'Cycling'), ('hiking', 'Hiking'), ('climbing', 'Climbing')], max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('trails', models.ManyToManyField(blank=True, null=True, to='trails.trail')),
            ],
        ),
    ]
