# Generated by Django 4.0.4 on 2022-06-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_trailtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trailtype',
            name='type',
            field=models.CharField(choices=[('climbing', 'Climbing'), ('hiking', 'Hiking'), ('cycling', 'Cycling')], max_length=50),
        ),
    ]
