# Generated by Django 4.0.4 on 2022-06-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_alter_trail_trail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_file',
            field=models.FileField(upload_to='djangodbmodelsfieldscharfield'),
        ),
    ]
