# Generated by Django 4.0.4 on 2022-06-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_alter_trailtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailtype',
            name='type',
            field=models.CharField(choices=[('hiking', 'Hiking'), ('cycling', 'Cycling'), ('climbing', 'Climbing')], max_length=50),
        ),
    ]
