# Generated by Django 4.0.4 on 2022-06-16 19:09

import django.core.validators
from django.db import migrations, models
import trails.models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_alter_trailtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=trails.models.thumb_location),
        ),
        migrations.AlterField(
            model_name='trail',
            name='trail_file',
            field=models.FileField(upload_to=trails.models.trail_file_location, validators=[django.core.validators.FileExtensionValidator(['geojson', 'gpx', 'js'])]),
        ),
        migrations.AlterField(
            model_name='trailtype',
            name='type',
            field=models.CharField(choices=[('cycling', 'Cycling'), ('hiking', 'Hiking'), ('climbing', 'Climbing')], max_length=50),
        ),
    ]
