# Generated by Django 4.0.4 on 2022-06-01 22:18

import django.core.validators
from django.db import migrations, models
import trails.models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_alter_trail_trail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_file',
            field=models.FileField(upload_to=trails.models.trail_file_location, validators=[django.core.validators.FileExtensionValidator(['geojson', 'gpx'])]),
        ),
    ]
