# Generated by Django 4.0.4 on 2022-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_photo_thumb_alter_trail_trail_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='share_future',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('link', 'Link')], default='private', max_length=7),
        ),
    ]
