# Generated by Django 4.0.4 on 2022-06-22 17:10

from django.db import migrations, models
import trails.models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0009_trail_share_future'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=512, upload_to=trails.models.photo_location),
        ),
        migrations.AlterField(
            model_name='trail',
            name='share',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('link', 'Share with link')], default='private', max_length=7),
        ),
        migrations.AlterField(
            model_name='trail',
            name='share_future',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('link', 'Share with link')], default='private', max_length=7),
        ),
        migrations.AlterField(
            model_name='trailtype',
            name='type',
            field=models.CharField(choices=[('hiking', 'Hiking'), ('climbing', 'Climbing'), ('cycling', 'Cycling')], max_length=50),
        ),
    ]
