# Generated by Django 4.0.4 on 2022-06-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0009_alter_trail_trail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
