# Generated by Django 4.0.4 on 2022-06-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_alter_photo_photo_alter_trail_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailtype',
            name='trails',
            field=models.ManyToManyField(to='trails.trail'),
        ),
        migrations.AlterField(
            model_name='trailtype',
            name='type',
            field=models.CharField(choices=[('cycling', 'Cycling'), ('climbing', 'Climbing'), ('hiking', 'Hiking')], max_length=50),
        ),
    ]
