# Generated by Django 4.0.4 on 2022-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_trail_max_lat_trail_max_lon_trail_min_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='heightmap',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
