# Generated by Django 4.0.4 on 2022-06-02 21:55

from django.db import migrations, models
import trails.models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0012_alter_trail_heightmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='mesh',
            field=models.FileField(blank=True, null=True, upload_to=trails.models.mesh_location),
        ),
        migrations.AlterField(
            model_name='trail',
            name='texture_sat',
            field=models.ImageField(blank=True, null=True, upload_to=trails.models.texture_sat_location),
        ),
        migrations.AlterField(
            model_name='trail',
            name='texture_trail',
            field=models.ImageField(blank=True, null=True, upload_to=trails.models.texture_trail_location),
        ),
    ]
