# Generated by Django 4.0.4 on 2022-06-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0013_alter_trail_mesh_alter_trail_texture_sat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
