# Generated by Django 4.0.4 on 2022-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_alter_waypoint_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='status_heightmap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='status_mesh',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='status_overall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='status_parsed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='status_texture_satellite',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='status_texture_trail',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trail',
            name='status_waypoints',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trail',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
