# Generated by Django 4.0.4 on 2022-06-22 17:24

from django.db import migrations, models
import trails.models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_alter_photo_photo_alter_trailtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=512, upload_to=trails.models.photo_location),
        ),
        migrations.AlterField(
            model_name='trailtype',
            name='type',
            field=models.CharField(choices=[('cycling', 'Cycling'), ('climbing', 'Climbing'), ('hiking', 'Hiking')], max_length=50),
        ),
    ]
