# Generated by Django 4.0.4 on 2022-06-03 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0016_waypoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
